In [2]:
import numpy as np
import pandas as pd

## Data Types and Attributes

In [3]:
# NumPy's main datatyepe is ndarry
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [4]:
a2 = np.array([[1,2.0,3.0],
              [4,5.0,6.5]])


In [5]:
a3 = np.array([[[1,2,3],
                [4,5,6],
                [7,8,9]],
               [[10,11,12],
                [13,14,15],
               [16,17,18]]])

In [14]:
a1.shape

(3,)

In [15]:
a2.shape

(2, 3)

In [16]:
a3.shape

(2, 3, 3)

In [17]:
#ndim means dimension
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [18]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [19]:
type(a1),type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [23]:
# Create a DataFrame from NumPy Array
df =pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.0
1  4.0  5.0  6.5

# 2. Creating Arrays

In [4]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [6]:
sample_array.dtype

dtype('int32')

In [7]:
ones = np.ones((3,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [8]:
ones.dtype

dtype('float64')

In [9]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
range_array = np.arange(1,10,2)
range_array

array([1, 3, 5, 7, 9])

In [14]:
random_array = np.random.randint(0,10, size =(3,4))
random_array

array([[2, 5, 1, 9],
       [6, 2, 2, 5],
       [7, 5, 5, 4]])

In [15]:
random_array.size

12

In [16]:
random_array.shape

(3, 4)

In [18]:
random_array2 = np.random.random((5,3))
random_array2

array([[0.13687226, 0.59551183, 0.55773357],
       [0.53261029, 0.43778132, 0.00361368],
       [0.56545423, 0.6648425 , 0.26727327],
       [0.39308333, 0.77902669, 0.79405915],
       [0.22578808, 0.84864626, 0.11927275]])

In [20]:
random_array3 = np.random.rand(5,3)
random_array3

array([[0.53828025, 0.93124821, 0.15387918],
       [0.23123886, 0.95660893, 0.04235614],
       [0.33135089, 0.73369163, 0.53093379],
       [0.25699194, 0.71974287, 0.02912618],
       [0.5445772 , 0.88931547, 0.55526308]])

In [34]:
# Pseudo-Random Numbers
np.random.seed(seed = 120)
# To stop the change of the Array items
random_array4 = np.random.randint(10, size=(5,3))
random_array4

array([[7, 0, 8],
       [4, 1, 7],
       [1, 3, 8],
       [9, 4, 9],
       [9, 6, 7]])

In [39]:
np.random.seed(5)
random_array5 = np.random.rand(3,4)
random_array5

array([[0.22199317, 0.87073231, 0.20671916, 0.91861091],
       [0.48841119, 0.61174386, 0.76590786, 0.51841799],
       [0.2968005 , 0.18772123, 0.08074127, 0.7384403 ]])

## Viewing Arrays and Matricies

In [40]:
np.unique(random_array4)

array([0, 1, 3, 4, 6, 7, 8, 9])

In [43]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [44]:
a3.shape

(2, 3, 3)

In [51]:
a3[:1, :2, :3]

array([[[1, 2, 3],
        [4, 5, 6]]])

In [47]:
a3[:2, :1]

array([[[ 1,  2,  3]],

       [[10, 11, 12]]])

In [69]:
a4 = np.random.randint(9, size=(2,3,3,5))
a4

array([[[[2, 4, 0, 8, 3],
         [1, 5, 4, 3, 7],
         [7, 0, 1, 2, 4]],

        [[6, 0, 7, 3, 5],
         [4, 5, 8, 2, 3],
         [5, 0, 3, 0, 6]],

        [[6, 5, 4, 5, 7],
         [8, 0, 3, 3, 6],
         [8, 4, 2, 3, 5]]],


       [[[1, 6, 5, 0, 0],
         [0, 6, 5, 6, 7],
         [2, 4, 8, 1, 8]],

        [[4, 4, 4, 7, 0],
         [7, 3, 5, 3, 1],
         [2, 5, 2, 4, 1]],

        [[4, 5, 0, 1, 6],
         [5, 7, 6, 1, 2],
         [3, 5, 8, 3, 2]]]])

In [65]:
a4.shape, a4.ndim

((2, 3, 3, 4), 4)

In [71]:
# Get the first Three numbers of the innermost array.
a4[:, :, :, :3]

array([[[[2, 4, 0],
         [1, 5, 4],
         [7, 0, 1]],

        [[6, 0, 7],
         [4, 5, 8],
         [5, 0, 3]],

        [[6, 5, 4],
         [8, 0, 3],
         [8, 4, 2]]],


       [[[1, 6, 5],
         [0, 6, 5],
         [2, 4, 8]],

        [[4, 4, 4],
         [7, 3, 5],
         [2, 5, 2]],

        [[4, 5, 0],
         [5, 7, 6],
         [3, 5, 8]]]])

In [85]:
a4[:2, :3, :2, :4]

array([[[[2, 4, 0, 8],
         [1, 5, 4, 3]],

        [[6, 0, 7, 3],
         [4, 5, 8, 2]],

        [[6, 5, 4, 5],
         [8, 0, 3, 3]]],


       [[[1, 6, 5, 0],
         [0, 6, 5, 6]],

        [[4, 4, 4, 7],
         [7, 3, 5, 3]],

        [[4, 5, 0, 1],
         [5, 7, 6, 1]]]])

# Manipulating & Comparing Arrays

### Arithmatics

In [89]:
a1

array([1, 2, 3])

In [8]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [91]:
a1 + ones

array([2., 3., 4.])

In [92]:
a1 - ones

array([0., 1., 2.])

In [93]:
a2

array([[1. , 2. , 3. ],
       [4. , 5. , 6.5]])

In [94]:
a1 * a2

array([[ 1. ,  4. ,  9. ],
       [ 4. , 10. , 19.5]])

In [6]:
a2 ** 2

array([[ 1.  ,  4.  ,  9.  ],
       [16.  , 25.  , 42.25]])

In [7]:
np.square(a2)

array([[ 1.  ,  4.  ,  9.  ],
       [16.  , 25.  , 42.25]])

In [10]:
a1 + ones

array([2., 3., 4.])

In [11]:
np.add(a1, ones)

array([2., 3., 4.])

In [12]:
a1 % 2

array([1, 0, 1], dtype=int32)

In [13]:
a1/2

array([0.5, 1. , 1.5])

In [14]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [15]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])

### Aggregation
Aggregation = Performing the same operation on a number of things

In [16]:
listy_list=[1,2,3]
type(listy_list)

list

In [18]:
sum(listy_list)

6

In [19]:
a1

array([1, 2, 3])

In [20]:
sum(a1)

6

In [21]:
np.sum(a1)

6

### Use Python methods ('sum()') on pyhton datatypes and use NumPy methods on NumPy arrays ('np.sum()').

In [23]:
# Create a Massive NumPy Array
massive_array = np.random.rand(10000)
massive_array.size

10000

In [25]:
massive_array[:10]

array([0.18641287, 0.95871696, 0.56953528, 0.92205053, 0.34973642,
       0.55459183, 0.56533684, 0.2447327 , 0.05484166, 0.96800063])

In [28]:
%timeit sum(massive_array) # Python's sum()
%timeit np.sum(massive_array) # NumPy's sum()

820 µs ± 6.58 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
8.09 µs ± 199 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [29]:
a2

array([[1. , 2. , 3. ],
       [4. , 5. , 6.5]])

In [37]:
np.mean(a2)

3.5833333333333335

In [38]:
np.max(a2)

6.5

In [39]:
np.min(a2)

1.0

In [40]:
# Standard Deviation = a measure of how spread out a group of numbers is from the mean.
np.std(a2)

1.8352262954621035

In [41]:
# Variance = Measure of the average degree to which each number is different from the mean.
# Higher Variance = Wider range of number.
# Lower Variance  = Lower range of number.
np.var(a2)

3.368055555555556

In [42]:
# Standard Deviation = Square root of Variance
np.sqrt(np.var(a2))

1.8352262954621035